[package]
name = "sourcerenderer_sdl"
version = "0.1.0"
authors = ["Robin Kertels <robin.kertels@gmail.com>"]
build = "build.rs"

[dependencies]
sdl2 = "0.34.2"
sdl2-sys = "0.34.2"
ash = "0.29.0"
sourcerenderer_bsp = { path = "../../bsp" }
sourcerenderer_engine = { path = "../../engine" }
sourcerenderer_core = { path = "../../core" }
sourcerenderer_vulkan = { path = "../../graphics/vulkan" }

