[package]
name = "sourcerenderer_engine"
version = "0.1.0"
authors = ["Robin Kertels <robin.kertels@gmail.com>"]
build = "build.rs"
edition = "2018"

[dependencies]
nalgebra = "0.22.0"
num_cpus = "1.13.0"
sourcerenderer_core = { path = "../core" }
sourcerenderer_vulkan = { path = "../graphics/vulkan" }
image = "0.23.2"
crossbeam-channel = "0.5.0"
crossbeam-utils = "0.8.0"
sourcerenderer_bsp = { path = "../valve_formats/bsp" }
sourcerenderer_vpk = { path = "../valve_formats/vpk" }
sourcerenderer_vtf = { path = "../valve_formats/vtf" }
sourcerenderer_vmt = { path = "../valve_formats/vmt" }
sourcerenderer_mdl = { path = "../valve_formats/mdl" }
legion = "0.3.1"
regex = "1.4.2"

[dependencies.async-std]
version = "1.6.1"
features = ["unstable"]
