[package]
name = "sourcerenderer_engine"
version = "0.1.0"
authors = ["Robin Kertels <robin.kertels@gmail.com>"]
build = "build.rs"
edition = "2018"

[dependencies]
vek = "0.9.11"
num_cpus = "1.11.1"
sourcerenderer_core = { path = "../core" }
sourcerenderer_vulkan = { path = "../graphics/vulkan" }
image = "0.23.2"
nalgebra = "0.18"

[dependencies.async-std]
version = "1.5.0"
features = ["unstable"]