[package]
name = "sourcerenderer_engine"
version = "0.1.0"
authors = ["Robin Kertels <robin.kertels@gmail.com>"]
edition = "2018"

[dependencies]
vek = "0.9.11"
num_cpus = "1.11.1"
sourcerenderer_core = { path = "../core" }
sourcerenderer_vulkan = { path = "../graphics/vulkan" }
tokio = { version = "0.2", features = ["full"] }