[package]
name = "sourcerenderer_web"
version = "0.1.0"
authors = ["Robin Kertels <robin.kertels@gmail.com>"]
edition = "2018"

[dependencies]
sourcerenderer_engine = { path = "../../engine" }
sourcerenderer_core = { path = "../../core" }

