[package]
name = "sourcerenderer_core"
version = "0.1.0"
authors = ["Robin Kertels <robin.kertels@gmail.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.22.0"
bitflags = "1.2.1"
bitset-core = "0.1.1"
crossbeam-channel = "0.5.0"
crossbeam-queue = "0.2.1"
crossbeam-deque = "0.7.3"
crossbeam-utils = "0.7.2"
num_cpus = "1.13.0"
rayon = "1.4.1"
