[package]
name = "sourcerenderer_core"
version = "0.1.0"
authors = ["Robin Kertels <robin.kertels@gmail.com>"]

[dependencies]
vek = "0.9.11"
bitflags = "1.2.1"
crossbeam-channel = "0.4.2"
crossbeam-queue = "0.2.1"
crossbeam-deque = "0.7.3"
crossbeam-utils = "0.7.2"
