[package]
name = "sourcerenderer_bsp"
version = "0.1.0"
authors = ["Robin <robin.kertels@outlook.com>"]

[dependencies]
byteorder = "1.3.1"
num-traits = "0.2.6"
num-derive = "0.2.4"
bitflags = "1.0.4"
