[package]
name = "sourcerenderer_bsp"
version = "0.1.0"
authors = ["Robin Kertels <robin.kertels@gmail.com>"]

[dependencies]
byteorder = "1.3.2"
num-traits = "0.2.10"
num-derive = "0.3.0"
bitflags = "1.2.1"
nalgebra = "0.18"
