[package]
name = "sourcerenderer_vulkan"
version = "0.1.0"
authors = ["Robin <robin.kertels@outlook.com>"]
edition = "2018"

[dependencies]
ash = "0.28.0"
sourcerenderer_core = { path = "../../core" }
vk-mem = "0.1.6"
