[package]
name = "sourcerenderer_vulkan"
version = "0.1.0"
authors = ["Robin <robin.kertels@outlook.com>"]
edition = "2018"

[dependencies]
ash = "0.27.1"
sourcerenderer_core = { path = "../../core" }
downcast-rs = "1.0.3"
vk-mem = { path = "../../../vk-mem-rs" }
