[package]
name = "sourcerenderer_vulkan"
version = "0.1.0"
authors = ["Robin Kertels <robin.kertels@gmail.com>"]
edition = "2018"

[dependencies]
ash = "0.29.0"
sourcerenderer_core = { path = "../../core" }
vk-mem = "0.1.8"
spin = "0.5.2"
