name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install glslang
      run: apt install glslang-tools
    - name: Install sdl
      run: apt install sdl2
    - name: Install clippy
      run: rustup component add clippy
    - name: Build
      run: cargo build --verbose
    - name: Lint
      run: cargo clippy
#    - name: Run tests
#      run: cargo test --verbose
